2019-02-08 04:37:07,579 - ERROR - QtestAgent.py - 145 - automationTypeHistory - RestFacade: Unsupported response code 500, url: https://demoqtesturl.qtestnet.com/api/v3/projects/84785/histories?page=1&pageSize=100, response received: {"message":"No row with the given identifier exists: [tc.model.Project#84785]"}
2019-02-08 04:38:13,112 - ERROR - QtestAgent.py - 145 - automationTypeHistory - RestFacade: Unsupported response code 500, url: https://demoqtesturl.qtestnet.com/api/v3/projects/84785/histories?page=1&pageSize=100, response received: {"message":"No row with the given identifier exists: [tc.model.Project#84785]"}
